//------------------------------------------------------------------------------
// <auto-generated>
//     이 코드는 템플릿에서 생성되었습니다.
//
//     이 파일을 수동으로 변경하면 응용 프로그램에서 예기치 않은 동작이 발생할 수 있습니다.
//     이 파일을 수동으로 변경하면 코드가 다시 생성될 때 변경 내용을 덮어씁니다.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FoodAppDotNet.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class STORE
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public STORE()
        {
            this.FOOD_DETAIL = new HashSet<FOOD_DETAIL>();
        }
    
        public int IDX { get; set; }
        public int COUNTRY_IDX { get; set; }
        public string STORE_KOR_NAME { get; set; }
        public string STORE_DELIVERY_TIP { get; set; }
        public string STORE_DELIVERY_MIN_TIME { get; set; }
        public string STORE_DELIVERY_MAX_TIME { get; set; }
        public Nullable<int> STORE_RATING { get; set; }
        public Nullable<System.DateTime> REGDATE { get; set; }
        public string REGID { get; set; }
        public Nullable<System.DateTime> UPDDATE { get; set; }
        public string UPDID { get; set; }
        public string ISUSE { get; set; }
        public string ETC { get; set; }
    
        public virtual COUNTRY COUNTRY { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FOOD_DETAIL> FOOD_DETAIL { get; set; }
    }
}
